version: "3"

services:
  laravel-app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MTSQL_DATABASE: laravel
      MTSQL_ROOT_PASSWORD: laravel
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
